### ISSUE TITLE
Issues with applying to my case

### ISSUE THREAD

**Issue by 1208overlord** [adipandas/multi-object-tracker#20]
Hello
I want to use this algorithm to track the hand to count the casher's operation on the casher.
But tracking ID is changing continuously.
Please help me how I can fix this issue.
Can I use this algorithm for my application?

[label.zip](https://github.com/adipandas/multi-object-tracker/files/5996293/label.zip)
https://sendgb.com/Az2jkxblEru

**Comment by 1208overlord** [comment]
https://sendgb.com/uljHgJdMyp2
This is the result video of running that algorithm.

**Comment by adipandas** [comment]
Hi @1208overlord, 

This is nice work. :+1: 

You will have to play around with the hyper-parameters of the multi-object tracker. As the MOT algorithms in this repository do not use any visual features, it is very likely you will face this problem for objects which are close to each other.

It may also be beneficial to implement something which can exploit image features. One of the example which I can think of is [this work](https://www.aaai.org/ocs/index.php/AAAI/AAAI17/paper/viewFile/14184/14304). I haven't gotten a chance to implement this yet. But it may solve your tracking problem since you can train your network to track using image features. 

Also, i believe you are using the default tracker. I suggest you to try `SORT` tracker.
I hope this resolves your issue.

Best,
Aditya.

**Comment by 1208overlord** [comment]
The above result is from SORT tracker.
can I get the more accurate result?
