### ISSUE TITLE
How did you choose the Process & Measurement noise?

### ISSUE THREAD

**Issue by cnavarrete** [adipandas/multi-object-tracker#24]
I've been using the Sort tracker since it fits my problem but I have the following problem, even though all my objects go from top to bottom in a mostly straight line (no exceptions), in some frames the predicions generate a bbox that goes up, which I find very odd. This kind of bbox is too far away from the detected bbox so it count as a new object to track. Is there a way to manipulate the predictions torwards a direction? How did you choose your parameters for the Kalman Filter?

Check this snippet, all it does is to simulate a bbox that moves 45-50 px (had to simulate some noise) down for 1000 frames, the IOU threshold is 0.2 so I think that it should work, but it does not. To print the bbox predicted I just added a line to sort_tracker.py after
```python
bb = self.tracks[track_id].predict()
```
This is only to demonstrate that in some frames the prediction goes up. The first 2-3 frames are critical for my app, which is a problem since most of the time this frame's bbox Y coordinate is predicted incorrectly as going up.

``` python
from motrackers import SORT
from argparse import Namespace
import numpy as np
import random

# x, y, w, h
bbox = [100, 100, 200, 100]

params = {
    'max_lost': 0,
    'tracker_output_format': 'mot_challenge',
    'iou_threshold': 0.2,
    'process_noise_scale': 1,
    'measurement_noise_scale': 1,
    'time_step': 1
}

params = Namespace(**params)

tracker = SORT(
            max_lost=params.max_lost,
            tracker_output_format=params.tracker_output_format,
            iou_threshold=params.iou_threshold,
            process_noise_scale=params.process_noise_scale,
            measurement_noise_scale=params.measurement_noise_scale,
            time_step=1
        )

for i in range(0, 1000):
    detection_bboxes = []
    detection_confidences = []
    detection_class_ids = []

    detection_bboxes.append(bbox)
    detection_confidences.append(1)
    detection_class_ids.append(0)

    detection_bboxes = np.array(detection_bboxes)
    detection_confidences = np.array(detection_confidences)
    detection_class_ids = np.array(detection_class_ids)
    
    tracks = tracker.update(detection_bboxes, detection_confidences, detection_class_ids)

    print(tracks)

    bbox = [bbox[0] + random.randint(-1, 1), bbox[1] + random.randint(45, 50), 200, 100]
```

Also I'm pretty surprised that rarely some bboxes predicted contain negative values for width and/or height in my actual app, too bad I couldn't simulate it.

**Comment by adipandas** [comment]
@cnavarrete I think the negative values for the width and height may happen because of Kalman Filter. KF tracks both, (X, Y) pixel locations as well as (width, height). To avoid that, you may try to reduce covariance of the width and height. Since the Gaussian has domain of [- infinity,  - infinity], the values may go to negative. You may need to handle that explicitly in your code depending on the use case.

I did implement the Tracker similar to what was used in SORT paper a while ago. But never tested it. You can find the code [[here](https://github.com/adipandas/multi-object-tracker/blob/53b908f9426298e7c3bc646320e8338b2e0309ab/motrackers/kalman_tracker.py#L195)]. As opposed to what is currently used in my SORT implementation, [[this](https://github.com/adipandas/multi-object-tracker/blob/53b908f9426298e7c3bc646320e8338b2e0309ab/motrackers/kalman_tracker.py#L195)] tracks (X, Y, aspect_ratio, area) as the parameters as used in paper.

And for initial deviation of KF, i think it may happen because of noisy measurements. Although I am not sure yet and will  have to go through your case in detail.
