### ISSUE TITLE
Print label and id of detected object

### ISSUE THREAD

**Issue by alisurajaya** [adipandas/multi-object-tracker#7]
How to print the object ID and label from detected object? I'm trying to get output like this (for example: ID0 car, ID1 car, ID2 person, ID3 motorcycle)

**Comment by adipandas** [comment]
Hello @alisurajaya : Sorry for the delay in response.  You will have to update some code in `Start object detection and tracking` block of your notebook to keep track of labels along with IDs.

I wasn't able to update this repo since quite sometime. I will try to do it over the coming weekend and update the codes. 

You can also send in a pull request.  I will be happy to accept your contribution. ☺️ 

Thank you.
~ Aditya

**Comment by adipandas** [comment]
Hi @alisurajaya, I finally updated the tracker to enable logs of tracked objects.
Please refer [this code](https://github.com/adipandas/multi-object-tracker/blob/master/examples/SimpleTracker2-caffe-model-mobilenetSSD.ipynb) for more details.
You can log it in any `.csv` or `.txt` file as per your convenience.

Best regards,
Aditya.
