### ISSUE TITLE
Question about Yolov3+Trackers

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [adipandas/multi-object-tracker#9]
Hi, 
    Thank you for the great work.  I am using Yolov3+DeepSort but it is very slow. My target is to use detection+tracking in the real-time. 
1-What kind of tracker are you using? Is it traditional methods or deep learning based trackers? 
2-Can I use this project in Nvidia Xavier NX? If yes then is there any additional requirements? 
3-What about the speed of yolov3+SimplTracker and yolov3+SimpleTracker2? 
4-What is the difference between SimpleTracker and SimpleTracker2

**Comment by adipandas** [comment]
Hi,
Since deepSORT uses neural network to identify the previously detected objects, it will be slow and speed will likely depend on your available compute.

1. In current versions, for `SimpleTracker` and `SimpleTracker2`, I am using greedy tracking approach (Nearest neighbor is assigned the ID from previous frame). It is not using deep learning based trackers. Here, only detection uses deep learning.
2. I believe you will be able to use this project on NVIDIA Xavier NX. I have not tried it personally. But as long as you are able to install as dependencies mentioned in the readme, it should work. I have tried keeping the _tracker_ dependencies as `opencv, numpy, scipy`. You should not need any additional packages.
3. I have plans to include the metrics for accuracy and speed. These are not available in current version. But as per my qualitative testing, I have observed that the speed of the trackers is preety much `60+` FPS. The detection part is the one which will influence your overall speed. For instance, in case you are able to run YOLOv3 network at `30` FPS, then the overall speed should be close to `25` to `30` FPS.
4. `SimpleTracker` and `SimpleTracker2` are the same. Only difference is that I included logging functionality to enable metric evaluations in `SimpleTracker2`.

I have also included the `IOU` tracker. Please check [this example](https://github.com/adipandas/multi-object-tracker/blob/master/examples/IOUTracker-caffe-model-mobilenetSSD.ipynb).

I am also planning to include Markov Process based trackers when the time permits.

You can try to replace the assignment of track-ids to the new detections from greedy approach to [Hungarian algorithm](https://en.wikipedia.org/wiki/Assignment_problem). It should improve the tracking accuracy as well.

Best,
Aditya.

**Comment by MuhammadAsadJaved** [comment]
@adipandas  Got it. Thank you for the answers.
